module.exports = {
    CMD_CONNECT: 0x01,
    CMD_DISCONNECT: 0x02,
    CMD_SPI_WRITE: 0x03,
    CMD_SPI_VERIFY: 0x04,
    CMD_FLASH: 0x05,
    CMD_WAIT: 0x06,
    CMD_DEC_COUNTER: 0x07,
    CMD_EEPROM: 0x08,
    CMD_END: 0xFF,

    RECORD_TYPE_DATA: 0x00,
    RECORD_TYPE_EOF: 0x01,
    RECORD_TYPE_EXT_SEGMENT_ADDRESS: 0x02,
    RECORD_TYPE_SEGMENT_START_ADDRESS: 0x03,
    RECORD_TYPE_EXT_LINEAR_ADDRESS: 0x04
}
